# Generated by Django 2.2.2 on 2019-06-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190626_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userdata',
        ),
    ]
