# Generated by Django 2.2.2 on 2019-06-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190626_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
